// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251224004202_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.AgendaItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "StartTime");

                    b.ToTable("AgendaItems", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.AgendaTrackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendaItemId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.ToTable("AgendaTracks", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RegisteredUsers")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RegistrationEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RegistrationStart")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__Events__3214EC07C821D3B6");

                    b.HasIndex("CreatedById");

                    b.HasIndex(new[] { "EventTypeId", "StartDateTime", "IsActive" }, "IX_Events_EventTypeId_StartDateTime_IsActive");

                    b.HasIndex(new[] { "StartDateTime" }, "IX_Events_StartDateTime_Active")
                        .HasFilter("([IsActive]=(1))");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            CreatedAt = new DateTime(2025, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Introductory workshop (past event)",
                            EndDateTime = new DateTime(2025, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            IsActive = true,
                            RegisteredUsers = 1,
                            RegistrationEnd = new DateOnly(2025, 9, 9),
                            RegistrationStart = new DateOnly(2025, 8, 20),
                            StartDateTime = new DateTime(2025, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Past Workshop: EF Core Basics",
                            UpdatedAt = new DateTime(2025, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 11, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Casual networking + food",
                            EndDateTime = new DateTime(2025, 12, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 2,
                            IsActive = true,
                            RegisteredUsers = 1,
                            RegistrationEnd = new DateOnly(2025, 12, 4),
                            RegistrationStart = new DateOnly(2025, 11, 15),
                            StartDateTime = new DateTime(2025, 12, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Networking Lunch",
                            UpdatedAt = new DateTime(2025, 11, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 12, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Outdoor team-building activity",
                            EndDateTime = new DateTime(2026, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 4,
                            IsActive = true,
                            RegisteredUsers = 0,
                            RegistrationEnd = new DateOnly(2026, 1, 9),
                            RegistrationStart = new DateOnly(2025, 12, 15),
                            StartDateTime = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Team Building Walk",
                            UpdatedAt = new DateTime(2025, 12, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 100,
                            CreatedAt = new DateTime(2025, 10, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Mandatory internal training",
                            EndDateTime = new DateTime(2025, 11, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 3,
                            IsActive = true,
                            RegisteredUsers = 1,
                            RegistrationEnd = new DateOnly(2025, 11, 24),
                            RegistrationStart = new DateOnly(2025, 11, 1),
                            StartDateTime = new DateTime(2025, 11, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Security Awareness Training",
                            UpdatedAt = new DateTime(2025, 10, 20, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Best practices discussion",
                            EndDateTime = new DateTime(2026, 2, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            IsActive = true,
                            RegisteredUsers = 0,
                            RegistrationEnd = new DateOnly(2026, 2, 2),
                            RegistrationStart = new DateOnly(2026, 1, 10),
                            StartDateTime = new DateTime(2026, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Lunch & Learn: Clean Code",
                            UpdatedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 10,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Optional wellness session",
                            EndDateTime = new DateTime(2025, 12, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 2,
                            IsActive = true,
                            RegisteredUsers = 1,
                            RegistrationEnd = new DateOnly(2025, 12, 19),
                            RegistrationStart = new DateOnly(2025, 12, 1),
                            StartDateTime = new DateTime(2025, 12, 20, 8, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Wellness Morning Yoga",
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 100,
                            CreatedAt = new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Upcoming features overview",
                            EndDateTime = new DateTime(2026, 3, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 3,
                            IsActive = true,
                            RegisteredUsers = 0,
                            RegistrationEnd = new DateOnly(2026, 3, 4),
                            RegistrationStart = new DateOnly(2026, 2, 10),
                            StartDateTime = new DateTime(2026, 3, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Product Roadmap Presentation",
                            UpdatedAt = new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Giving back together",
                            EndDateTime = new DateTime(2025, 10, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 4,
                            IsActive = true,
                            RegisteredUsers = 0,
                            RegistrationEnd = new DateOnly(2025, 10, 14),
                            RegistrationStart = new DateOnly(2025, 9, 20),
                            StartDateTime = new DateTime(2025, 10, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Community Volunteering Day",
                            UpdatedAt = new DateTime(2025, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Persistence.Entities.EventTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EventTag__3214EC07F32EF299");

                    b.HasIndex(new[] { "TagId" }, "IX_EventTags_TagId");

                    b.HasIndex(new[] { "EventId", "TagId" }, "UQ_EventTags")
                        .IsUnique();

                    b.ToTable("EventTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            TagId = 5
                        },
                        new
                        {
                            Id = 2,
                            EventId = 2,
                            TagId = 3
                        },
                        new
                        {
                            Id = 3,
                            EventId = 2,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("Persistence.Entities.EventTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__EventTyp__3214EC0726DF4889");

                    b.HasIndex(new[] { "Name" }, "UQ__EventTyp__737584F6755CCC5F")
                        .IsUnique();

                    b.ToTable("EventTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hands-on session",
                            IsActive = true,
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Community meetup",
                            IsActive = true,
                            Name = "Meetup"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Large multi-session event",
                            IsActive = true,
                            Name = "Conference"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Online session",
                            IsActive = true,
                            Name = "Webinar"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Internal team activity",
                            IsActive = true,
                            Name = "Team Building"
                        });
                });

            modelBuilder.Entity("Persistence.Entities.RegistrationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Registra__3214EC07B745E531");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "EventId", "StatusId" }, "IX_Registrations_EventId_StatusId");

                    b.HasIndex(new[] { "EventId", "UserId" }, "UQ_Registrations_EventUser_Active")
                        .IsUnique()
                        .HasFilter("([StatusId]>(3))");

                    b.ToTable("Registrations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            RegisteredAt = new DateTime(2025, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            EventId = 2,
                            RegisteredAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            EventId = 4,
                            RegisteredAt = new DateTime(2025, 11, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            EventId = 6,
                            RegisteredAt = new DateTime(2025, 12, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            EventId = 2,
                            RegisteredAt = new DateTime(2025, 11, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CancelledAt = new DateTime(2025, 8, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            RegisteredAt = new DateTime(2025, 8, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Persistence.Entities.RegistrationStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Registra__3214EC077CE0B27D");

                    b.HasIndex(new[] { "Name" }, "UQ__Registra__737584F6E6264F98")
                        .IsUnique();

                    b.ToTable("RegistrationStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Awaiting approval",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Description = "No spots currently available",
                            Name = "Waitlisted"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Registration cancelled",
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Spot confirmed",
                            Name = "Confirmed"
                        });
                });

            modelBuilder.Entity("Persistence.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Tags__3214EC07845EC1D8");

                    b.HasIndex(new[] { "Name" }, "UQ__Tags__737584F69205C21B")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "theme",
                            Name = "outdoor"
                        },
                        new
                        {
                            Id = 2,
                            Category = "theme",
                            Name = "team-building"
                        },
                        new
                        {
                            Id = 3,
                            Category = "perk",
                            Name = "free-food"
                        },
                        new
                        {
                            Id = 4,
                            Category = "theme",
                            Name = "networking"
                        },
                        new
                        {
                            Id = 5,
                            Category = "topic",
                            Name = "tech"
                        },
                        new
                        {
                            Id = 6,
                            Category = "topic",
                            Name = "wellness"
                        });
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07F44ED148");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534D7C521D4")
                        .IsUnique();

                    b.ToTable("DomainUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 2,
                            Email = "admin@demo.com",
                            FullName = "Demo Admin",
                            IsActive = true,
                            Role = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 4,
                            Email = "organizer@demo.com",
                            FullName = "Demo Organizer",
                            IsActive = true,
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 6,
                            Email = "employee1@demo.com",
                            FullName = "Demo Employee 1",
                            IsActive = true,
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 1,
                            Email = "employee2@demo.com",
                            FullName = "Demo Employee 2",
                            IsActive = true,
                            Role = 1
                        });
                });

            modelBuilder.Entity("Persistence.IdentityModels.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Organizer",
                            NormalizedName = "ORGANIZER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Persistence.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastOtpSentTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.Entities.AgendaItemEntity", b =>
                {
                    b.HasOne("Persistence.Entities.EventEntity", "Event")
                        .WithMany("Agendas")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Persistence.Entities.AgendaTrackEntity", b =>
                {
                    b.HasOne("Persistence.Entities.AgendaItemEntity", "AgendaItem")
                        .WithMany("Tracks")
                        .HasForeignKey("AgendaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaItem");
                });

            modelBuilder.Entity("Persistence.Entities.EventEntity", b =>
                {
                    b.HasOne("Persistence.Entities.UserEntity", "CreatedBy")
                        .WithMany("Events")
                        .HasForeignKey("CreatedById")
                        .IsRequired()
                        .HasConstraintName("FK__Events__CreatedB__4D94879B");

                    b.HasOne("Persistence.Entities.EventTypeEntity", "EventTypeEntity")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Events__EventTyp__4CA06362");

                    b.OwnsOne("Persistence.Entities.LocationEntity", "Location", b1 =>
                        {
                            b1.Property<int>("EventEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("AdditionalInformation")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("FloorNumber")
                                .HasColumnType("int");

                            b1.Property<int>("LocationType")
                                .HasColumnType("int");

                            b1.Property<int>("RoomNumber")
                                .HasColumnType("int");

                            b1.HasKey("EventEntityId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventEntityId");

                            b1.OwnsOne("Persistence.Entities.AddressEntity", "Address", b2 =>
                                {
                                    b2.Property<int>("LocationEntityEventEntityId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("VenueName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.HasKey("LocationEntityEventEntityId");

                                    b2.HasIndex("VenueName", "City");

                                    b2.ToTable("Events");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationEntityEventEntityId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("EventTypeEntity");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.Entities.EventTagEntity", b =>
                {
                    b.HasOne("Persistence.Entities.EventEntity", "EventEntity")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__EventTags__Event__571DF1D5");

                    b.HasOne("Persistence.Entities.TagEntity", "TagEntity")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK__EventTags__TagId__5812160E");

                    b.Navigation("EventEntity");

                    b.Navigation("TagEntity");
                });

            modelBuilder.Entity("Persistence.Entities.RegistrationEntity", b =>
                {
                    b.HasOne("Persistence.Entities.EventEntity", "EventEntity")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Event__5070F446");

                    b.HasOne("Persistence.Entities.RegistrationStatusEntity", "StatusEntity")
                        .WithMany("Registrations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Statu__52593CB8");

                    b.HasOne("Persistence.Entities.UserEntity", "UserEntity")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__UserI__5165187F");

                    b.Navigation("EventEntity");

                    b.Navigation("StatusEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("Persistence.Entities.UserEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Persistence.Entities.AgendaItemEntity", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Persistence.Entities.EventEntity", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("EventTags");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Persistence.Entities.EventTypeEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Persistence.Entities.RegistrationStatusEntity", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Persistence.Entities.TagEntity", b =>
                {
                    b.Navigation("EventTags");
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
