// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220091825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Persistence.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__Events__3214EC07C821D3B6");

                    b.HasIndex("CreatedById");

                    b.HasIndex(new[] { "EventTypeId", "StartDateTime", "IsActive" }, "IX_Events_EventTypeId_StartDateTime_IsActive");

                    b.HasIndex(new[] { "StartDateTime" }, "IX_Events_StartDateTime_Active")
                        .HasFilter("([IsActive]=(1))");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Persistence.Models.EventTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EventTag__3214EC07F32EF299");

                    b.HasIndex(new[] { "TagId" }, "IX_EventTags_TagId");

                    b.HasIndex(new[] { "EventId", "TagId" }, "UQ_EventTags")
                        .IsUnique();

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("Persistence.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__EventTyp__3214EC0726DF4889");

                    b.HasIndex(new[] { "Name" }, "UQ__EventTyp__737584F6755CCC5F")
                        .IsUnique();

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("Persistence.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Registra__3214EC07B745E531");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "EventId", "StatusId" }, "IX_Registrations_EventId_StatusId");

                    b.HasIndex(new[] { "EventId", "UserId" }, "UQ_Registrations_EventUser_Active")
                        .IsUnique()
                        .HasFilter("([StatusId]>(3))");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Persistence.Models.RegistrationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Registra__3214EC077CE0B27D");

                    b.HasIndex(new[] { "Name" }, "UQ__Registra__737584F6E6264F98")
                        .IsUnique();

                    b.ToTable("RegistrationStatuses");
                });

            modelBuilder.Entity("Persistence.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07C792DF41");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F654656A52")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Persistence.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Tags__3214EC07845EC1D8");

                    b.HasIndex(new[] { "Name" }, "UQ__Tags__737584F69205C21B")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Persistence.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07F44ED148");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534D7C521D4")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Persistence.Models.Event", b =>
                {
                    b.HasOne("Persistence.Models.User", "CreatedBy")
                        .WithMany("Events")
                        .HasForeignKey("CreatedById")
                        .IsRequired()
                        .HasConstraintName("FK__Events__CreatedB__4D94879B");

                    b.HasOne("Persistence.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Events__EventTyp__4CA06362");

                    b.Navigation("CreatedBy");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("Persistence.Models.EventTag", b =>
                {
                    b.HasOne("Persistence.Models.Event", "Event")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__EventTags__Event__571DF1D5");

                    b.HasOne("Persistence.Models.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK__EventTags__TagId__5812160E");

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Persistence.Models.Registration", b =>
                {
                    b.HasOne("Persistence.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Event__5070F446");

                    b.HasOne("Persistence.Models.RegistrationStatus", "Status")
                        .WithMany("Registrations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Statu__52593CB8");

                    b.HasOne("Persistence.Models.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__UserI__5165187F");

                    b.Navigation("Event");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Models.User", b =>
                {
                    b.HasOne("Persistence.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__44FF419A");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Persistence.Models.Event", b =>
                {
                    b.Navigation("EventTags");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Persistence.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Persistence.Models.RegistrationStatus", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Persistence.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Persistence.Models.Tag", b =>
                {
                    b.Navigation("EventTags");
                });

            modelBuilder.Entity("Persistence.Models.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
