// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.AgendaItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "StartTime");

                    b.ToTable("AgendaItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "Pick up materials and settle in.",
                            Duration = new TimeSpan(0, 0, 15, 0, 0),
                            EventId = 1,
                            Location = "Lobby",
                            StartTime = new TimeOnly(10, 0, 0),
                            Title = "Registration & Coffee",
                            Type = 5
                        },
                        new
                        {
                            Id = 102,
                            Description = "DbContext, tracking, and basic mappings.",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            EventId = 1,
                            Location = "Room 4",
                            StartTime = new TimeOnly(10, 15, 0),
                            Title = "EF Core Fundamentals",
                            Type = 1
                        },
                        new
                        {
                            Id = 103,
                            Description = "Build a small model + migrations + queries.",
                            Duration = new TimeSpan(0, 0, 50, 0, 0),
                            EventId = 1,
                            Location = "Room 4",
                            StartTime = new TimeOnly(11, 5, 0),
                            Title = "Hands-on Lab",
                            Type = 2
                        },
                        new
                        {
                            Id = 201,
                            Description = "Snacks + meet the community.",
                            Duration = new TimeSpan(0, 0, 20, 0, 0),
                            EventId = 2,
                            Location = "Main Hall",
                            StartTime = new TimeOnly(17, 0, 0),
                            Title = "Welcome & Networking",
                            Type = 5
                        },
                        new
                        {
                            Id = 202,
                            Description = "Short talks from multiple speakers.",
                            Duration = new TimeSpan(0, 0, 40, 0, 0),
                            EventId = 2,
                            Location = "Main Hall",
                            StartTime = new TimeOnly(17, 20, 0),
                            Title = "Talks: GraphQL in Production",
                            Type = 6
                        },
                        new
                        {
                            Id = 203,
                            Description = "Bring your questions.",
                            Duration = new TimeSpan(0, 0, 40, 0, 0),
                            EventId = 2,
                            Location = "Main Hall",
                            StartTime = new TimeOnly(18, 10, 0),
                            Title = "Open Q&A",
                            Type = 6
                        },
                        new
                        {
                            Id = 301,
                            Description = "Live Q&A + examples.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            EventId = 3,
                            Location = "Online",
                            StartTime = new TimeOnly(16, 0, 0),
                            Title = "Clean Architecture Q&A",
                            Type = 6
                        },
                        new
                        {
                            Id = 302,
                            Description = "Links and next steps.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            EventId = 3,
                            Location = "Online",
                            StartTime = new TimeOnly(17, 0, 0),
                            Title = "Wrap-up & Resources",
                            Type = 7
                        },
                        new
                        {
                            Id = 401,
                            Description = "Verify Docker desktop + repo clone.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            EventId = 4,
                            Location = "Room 7 / Stream",
                            StartTime = new TimeOnly(9, 0, 0),
                            Title = "Intro + Setup",
                            Type = 1
                        },
                        new
                        {
                            Id = 402,
                            Description = "Containers, compose, debugging.",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EventId = 4,
                            Location = "Room 7 / Stream",
                            StartTime = new TimeOnly(9, 30, 0),
                            Title = "Hands-on Workshop",
                            Type = 2
                        },
                        new
                        {
                            Id = 501,
                            Description = "Read plans, fix slow queries.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            EventId = 5,
                            Location = "Room 3",
                            StartTime = new TimeOnly(13, 0, 0),
                            Title = "Query Tuning Clinic",
                            Type = 2
                        },
                        new
                        {
                            Id = 502,
                            Description = "Index strategy and pitfalls.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            EventId = 5,
                            Location = "Room 3",
                            StartTime = new TimeOnly(14, 0, 0),
                            Title = "Indexing Deep Dive",
                            Type = 1
                        },
                        new
                        {
                            Id = 601,
                            Description = "xUnit, Moq, and common patterns.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            EventId = 6,
                            Location = "Online",
                            StartTime = new TimeOnly(15, 0, 0),
                            Title = "Unit Testing Patterns",
                            Type = 2
                        },
                        new
                        {
                            Id = 602,
                            Description = "Refactor tests + coverage improvements.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            EventId = 6,
                            Location = "Online",
                            StartTime = new TimeOnly(16, 30, 0),
                            Title = "Hands-on Lab",
                            Type = 2
                        },
                        new
                        {
                            Id = 701,
                            Description = "Pitch ideas and form groups.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            EventId = 7,
                            Location = "Community Space",
                            StartTime = new TimeOnly(18, 0, 0),
                            Title = "Kickoff & Team Forming",
                            Type = 5
                        },
                        new
                        {
                            Id = 702,
                            Description = "Ship something small.",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            EventId = 7,
                            Location = "Community Space",
                            StartTime = new TimeOnly(18, 30, 0),
                            Title = "Build Session",
                            Type = 5
                        },
                        new
                        {
                            Id = 801,
                            Description = "Pipeline basics and environments.",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            EventId = 8,
                            Location = "Cloud Lab / Stream",
                            StartTime = new TimeOnly(10, 0, 0),
                            Title = "CI/CD Overview",
                            Type = 1
                        },
                        new
                        {
                            Id = 802,
                            Description = "Deploy end-to-end.",
                            Duration = new TimeSpan(0, 3, 15, 0, 0),
                            EventId = 8,
                            Location = "Cloud Lab / Stream",
                            StartTime = new TimeOnly(10, 45, 0),
                            Title = "Deploy Walkthrough",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Persistence.Entities.AgendaTrackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendaItemId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.ToTable("AgendaTracks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            AgendaItemId = 103,
                            Room = "Room 4",
                            Speaker = "Beka Ghvaberidze",
                            Title = "Track A: Migrations"
                        },
                        new
                        {
                            Id = 1002,
                            AgendaItemId = 103,
                            Room = "Room 4",
                            Speaker = "Giorgi Tamarashvili",
                            Title = "Track B: LINQ Queries"
                        },
                        new
                        {
                            Id = 2001,
                            AgendaItemId = 202,
                            Room = "Main Hall",
                            Speaker = "Lasha Daushvili",
                            Title = "GraphQL Schema Design"
                        },
                        new
                        {
                            Id = 2002,
                            AgendaItemId = 202,
                            Room = "Main Hall",
                            Speaker = "Dimitri Dondoladze",
                            Title = "Caching & Performance"
                        },
                        new
                        {
                            Id = 4001,
                            AgendaItemId = 402,
                            Room = "Room 7 / Stream",
                            Speaker = "James Richardson",
                            Title = "Docker Compose & Environment Variables"
                        },
                        new
                        {
                            Id = 4002,
                            AgendaItemId = 402,
                            Room = "Room 7 / Stream",
                            Speaker = "Elena Novak",
                            Title = "Debugging Containers in .NET"
                        },
                        new
                        {
                            Id = 6001,
                            AgendaItemId = 601,
                            Room = "Online",
                            Speaker = "Lasha Daushvili",
                            Title = "Mocks vs Fakes"
                        },
                        new
                        {
                            Id = 6002,
                            AgendaItemId = 602,
                            Room = "Online",
                            Speaker = "Beka Ghvaberidze",
                            Title = "Refactoring Legacy Tests"
                        },
                        new
                        {
                            Id = 8001,
                            AgendaItemId = 802,
                            Room = "Cloud Lab / Stream",
                            Speaker = "Andrei Popescu",
                            Title = "CI/CD Pipeline Setup"
                        },
                        new
                        {
                            Id = 8002,
                            AgendaItemId = 802,
                            Room = "Cloud Lab / Stream",
                            Speaker = "Natalie Wong",
                            Title = "Deployment & Rollback Strategies"
                        });
                });

            modelBuilder.Entity("Persistence.Entities.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("NotificationSettings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RegisteredUsers")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RegistrationEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RegistrationStart")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__Events__3214EC07C821D3B6");

                    b.HasIndex("CreatedById");

                    b.HasIndex(new[] { "EventTypeId", "StartDateTime", "IsActive" }, "IX_Events_EventTypeId_StartDateTime_IsActive");

                    b.HasIndex(new[] { "StartDateTime" }, "IX_Events_StartDateTime_Active")
                        .HasFilter("([IsActive]=(1))");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            CreatedAt = new DateTime(2025, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Introductory workshop (past event)",
                            EndDateTime = new DateTime(2025, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            IsActive = true,
                            RegisteredUsers = 1,
                            RegistrationEnd = new DateOnly(2025, 9, 9),
                            RegistrationStart = new DateOnly(2025, 8, 20),
                            StartDateTime = new DateTime(2025, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Past Workshop: EF Core Basics",
                            UpdatedAt = new DateTime(2025, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 60,
                            CreatedAt = new DateTime(2025, 12, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Community meetup and short talks",
                            EndDateTime = new DateTime(2026, 1, 15, 19, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            ImageUrl = "https://pics.example.com/events/graphql.png",
                            IsActive = true,
                            RegisteredUsers = 1,
                            RegistrationEnd = new DateOnly(2026, 1, 14),
                            RegistrationStart = new DateOnly(2025, 12, 20),
                            StartDateTime = new DateTime(2026, 1, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            Title = "GraphQL Meetup: APIs in Practice",
                            UpdatedAt = new DateTime(2025, 12, 10, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 200,
                            CreatedAt = new DateTime(2026, 1, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Live Q&A + examples",
                            EndDateTime = new DateTime(2026, 2, 5, 17, 30, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            IsActive = true,
                            RegisteredUsers = 0,
                            RegistrationEnd = new DateOnly(2026, 2, 4),
                            RegistrationStart = new DateOnly(2026, 1, 10),
                            StartDateTime = new DateTime(2026, 2, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Virtual: Clean Architecture Q&A",
                            UpdatedAt = new DateTime(2026, 1, 5, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Hands-on + streaming",
                            EndDateTime = new DateTime(2026, 3, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            IsActive = true,
                            RegisteredUsers = 1,
                            RegistrationEnd = new DateOnly(2026, 3, 11),
                            RegistrationStart = new DateOnly(2026, 2, 10),
                            StartDateTime = new DateTime(2026, 3, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Hybrid: Docker for .NET Developers",
                            UpdatedAt = new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 9, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Indexing and query tuning",
                            EndDateTime = new DateTime(2025, 10, 22, 15, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            IsActive = true,
                            RegisteredUsers = 0,
                            RegistrationEnd = new DateOnly(2025, 10, 21),
                            RegistrationStart = new DateOnly(2025, 10, 1),
                            StartDateTime = new DateTime(2025, 10, 22, 13, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Past: SQL Performance Clinic",
                            UpdatedAt = new DateTime(2025, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 300,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "xUnit + Moq + patterns",
                            EndDateTime = new DateTime(2026, 4, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            ImageUrl = "https://pics.example.com/events/testing.png",
                            IsActive = true,
                            RegisteredUsers = 1,
                            RegistrationEnd = new DateOnly(2026, 4, 7),
                            RegistrationStart = new DateOnly(2026, 3, 10),
                            StartDateTime = new DateTime(2026, 4, 8, 15, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Virtual: Unit Testing Masterclass",
                            UpdatedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 80,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Bring a project, ship something",
                            EndDateTime = new DateTime(2026, 5, 20, 21, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            IsActive = true,
                            RegisteredUsers = 0,
                            RegistrationEnd = new DateOnly(2026, 5, 19),
                            RegistrationStart = new DateOnly(2026, 4, 20),
                            StartDateTime = new DateTime(2026, 5, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "In-Person: Hack Night",
                            UpdatedAt = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 50,
                            CreatedAt = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "CI/CD + deploy walkthrough",
                            EndDateTime = new DateTime(2026, 6, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1,
                            ImageUrl = "https://pics.example.com/events/cloud.png",
                            IsActive = true,
                            RegisteredUsers = 0,
                            RegistrationEnd = new DateOnly(2026, 6, 10),
                            RegistrationStart = new DateOnly(2026, 5, 10),
                            StartDateTime = new DateTime(2026, 6, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Hybrid: Cloud Deployment Workshop",
                            UpdatedAt = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Persistence.Entities.EventTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EventTag__3214EC07F32EF299");

                    b.HasIndex(new[] { "TagId" }, "IX_EventTags_TagId");

                    b.HasIndex(new[] { "EventId", "TagId" }, "UQ_EventTags")
                        .IsUnique();

                    b.ToTable("EventTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            TagId = 5
                        },
                        new
                        {
                            Id = 2,
                            EventId = 2,
                            TagId = 3
                        },
                        new
                        {
                            Id = 3,
                            EventId = 2,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("Persistence.Entities.EventTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__EventTyp__3214EC0726DF4889");

                    b.HasIndex(new[] { "Name" }, "UQ__EventTyp__737584F6755CCC5F")
                        .IsUnique();

                    b.ToTable("EventTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hands-on session",
                            IsActive = true,
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Community meetup",
                            IsActive = true,
                            Name = "Meetup"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Large multi-session event",
                            IsActive = true,
                            Name = "Conference"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Online session",
                            IsActive = true,
                            Name = "Webinar"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Internal team activity",
                            IsActive = true,
                            Name = "Team Building"
                        });
                });

            modelBuilder.Entity("Persistence.Entities.RegistrationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Registra__3214EC07B745E531");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "EventId", "StatusId" }, "IX_Registrations_EventId_StatusId");

                    b.HasIndex(new[] { "EventId", "UserId" }, "UQ_Registrations_EventUser_Active")
                        .IsUnique()
                        .HasFilter("([StatusId]>(3))");

                    b.ToTable("Registrations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            RegisteredAt = new DateTime(2025, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            EventId = 2,
                            RegisteredAt = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            EventId = 4,
                            RegisteredAt = new DateTime(2025, 11, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            EventId = 6,
                            RegisteredAt = new DateTime(2025, 12, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            EventId = 2,
                            RegisteredAt = new DateTime(2025, 11, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CancelledAt = new DateTime(2025, 8, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            RegisteredAt = new DateTime(2025, 8, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Persistence.Entities.RegistrationStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Registra__3214EC077CE0B27D");

                    b.HasIndex(new[] { "Name" }, "UQ__Registra__737584F6E6264F98")
                        .IsUnique();

                    b.ToTable("RegistrationStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Awaiting approval",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Description = "No spots currently available",
                            Name = "Waitlisted"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Registration cancelled",
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Spot confirmed",
                            Name = "Confirmed"
                        });
                });

            modelBuilder.Entity("Persistence.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Tags__3214EC07845EC1D8");

                    b.HasIndex(new[] { "Name" }, "UQ__Tags__737584F69205C21B")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "theme",
                            Name = "outdoor"
                        },
                        new
                        {
                            Id = 2,
                            Category = "theme",
                            Name = "team-building"
                        },
                        new
                        {
                            Id = 3,
                            Category = "perk",
                            Name = "free-food"
                        },
                        new
                        {
                            Id = 4,
                            Category = "theme",
                            Name = "networking"
                        },
                        new
                        {
                            Id = 5,
                            Category = "topic",
                            Name = "tech"
                        },
                        new
                        {
                            Id = 6,
                            Category = "topic",
                            Name = "wellness"
                        });
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07F44ED148");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534D7C521D4")
                        .IsUnique();

                    b.ToTable("DomainUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 2,
                            Email = "admin@demo.com",
                            FullName = "Demo Admin",
                            IsActive = true,
                            Role = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 4,
                            Email = "organizer@demo.com",
                            FullName = "Demo Organizer",
                            IsActive = true,
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 6,
                            Email = "employee1@demo.com",
                            FullName = "Demo Employee 1",
                            IsActive = true,
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = 1,
                            Email = "employee2@demo.com",
                            FullName = "Demo Employee 2",
                            IsActive = true,
                            Role = 1
                        });
                });

            modelBuilder.Entity("Persistence.IdentityModels.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Organizer",
                            NormalizedName = "ORGANIZER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Persistence.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastOtpSentTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4013f38b-691b-4620-9707-a4f1575629d1",
                            Email = "admin@demo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DEMO.COM",
                            NormalizedUserName = "ADMIN@DEMO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIFDW6DmZyDAaerp5dk9SGTkLIyjmCZJYjEFSljvWg1g+hEkUy77/M995TwmIrGoBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b909d6d9-9c21-47af-8738-c7eeade67f4c",
                            TwoFactorEnabled = false,
                            UserName = "admin@demo.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "294c01f9-b0e1-4488-baba-f9a5a4fac90c",
                            Email = "organizer@demo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ORGANIZER@DEMO.COM",
                            NormalizedUserName = "ORGANIZER@DEMO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN3fblC6s4i16grF4oCAjaFKcYUxbJAS1vDht8DSckUKJ3o8bQTZvVV1cd8C41CM5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "59a6d2e3-e66b-4617-9586-91242743d02d",
                            TwoFactorEnabled = false,
                            UserName = "organizer@demo.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74793599-8491-41e6-861d-631e953b1d26",
                            Email = "employee1@demo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYEE1@DEMO.COM",
                            NormalizedUserName = "EMPLOYEE1@DEMO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZ218hpd1Yy0ro9q37BjYS8rx8+7z0wmlP4n69qktvvs2hJ8uFNPVoPFJqV7FxnNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4941a6de-4bda-4080-abe2-47917c3b62e9",
                            TwoFactorEnabled = false,
                            UserName = "employee1@demo.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "24df6cde-7939-4258-88ac-cf102e20ebd7",
                            Email = "employee2@demo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYEE2@DEMO.COM",
                            NormalizedUserName = "EMPLOYEE2@DEMO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIl2KxDTkFeXvT8LqazKRqDi0EmM7rH/c8LfFIPRdBEL2fFRhJnPBEUxaCa4y6bNmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "672fcc43-895f-4757-833c-705aa79fddbd",
                            TwoFactorEnabled = false,
                            UserName = "employee2@demo.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.Entities.AgendaItemEntity", b =>
                {
                    b.HasOne("Persistence.Entities.EventEntity", "Event")
                        .WithMany("Agendas")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Persistence.Entities.AgendaTrackEntity", b =>
                {
                    b.HasOne("Persistence.Entities.AgendaItemEntity", "AgendaItem")
                        .WithMany("Tracks")
                        .HasForeignKey("AgendaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaItem");
                });

            modelBuilder.Entity("Persistence.Entities.EventEntity", b =>
                {
                    b.HasOne("Persistence.Entities.UserEntity", "CreatedBy")
                        .WithMany("Events")
                        .HasForeignKey("CreatedById")
                        .IsRequired()
                        .HasConstraintName("FK__Events__CreatedB__4D94879B");

                    b.HasOne("Persistence.Entities.EventTypeEntity", "EventTypeEntity")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Events__EventTyp__4CA06362");

                    b.OwnsOne("Persistence.Entities.LocationEntity", "Location", b1 =>
                        {
                            b1.Property<int>("EventEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("AdditionalInformation")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("FloorNumber")
                                .HasColumnType("int");

                            b1.Property<int>("LocationType")
                                .HasColumnType("int");

                            b1.Property<int>("RoomNumber")
                                .HasColumnType("int");

                            b1.HasKey("EventEntityId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventEntityId");

                            b1.OwnsOne("Persistence.Entities.AddressEntity", "Address", b2 =>
                                {
                                    b2.Property<int>("LocationEntityEventEntityId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("VenueName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(450)");

                                    b2.HasKey("LocationEntityEventEntityId");

                                    b2.HasIndex("VenueName", "City");

                                    b2.ToTable("Events");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationEntityEventEntityId");

                                    b2.HasData(
                                        new
                                        {
                                            LocationEntityEventEntityId = 1,
                                            City = "Tbilisi",
                                            Street = "Gerdasd",
                                            VenueName = "Building"
                                        },
                                        new
                                        {
                                            LocationEntityEventEntityId = 2,
                                            City = "Tbilisi",
                                            Street = "Rustaveli Ave",
                                            VenueName = "Tech Hub"
                                        },
                                        new
                                        {
                                            LocationEntityEventEntityId = 3,
                                            City = "Remote",
                                            Street = "N/A",
                                            VenueName = "Online"
                                        },
                                        new
                                        {
                                            LocationEntityEventEntityId = 4,
                                            City = "Tbilisi",
                                            Street = "Chavchavadze",
                                            VenueName = "Conference Center"
                                        },
                                        new
                                        {
                                            LocationEntityEventEntityId = 5,
                                            City = "Tbilisi",
                                            Street = "Kazbegi Ave",
                                            VenueName = "DB Lab"
                                        },
                                        new
                                        {
                                            LocationEntityEventEntityId = 6,
                                            City = "Remote",
                                            Street = "N/A",
                                            VenueName = "Online"
                                        },
                                        new
                                        {
                                            LocationEntityEventEntityId = 7,
                                            City = "Tbilisi",
                                            Street = "Tamarashvili",
                                            VenueName = "Community Space"
                                        },
                                        new
                                        {
                                            LocationEntityEventEntityId = 8,
                                            City = "Tbilisi",
                                            Street = "Pekini Ave",
                                            VenueName = "Cloud Lab"
                                        });
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.HasData(
                                new
                                {
                                    EventEntityId = 1,
                                    AdditionalInformation = "Sigma",
                                    FloorNumber = 5,
                                    LocationType = 0,
                                    RoomNumber = 4
                                },
                                new
                                {
                                    EventEntityId = 2,
                                    AdditionalInformation = "Snacks provided",
                                    FloorNumber = 2,
                                    LocationType = 0,
                                    RoomNumber = 12
                                },
                                new
                                {
                                    EventEntityId = 3,
                                    AdditionalInformation = "Join link in email",
                                    FloorNumber = 0,
                                    LocationType = 1,
                                    RoomNumber = 0
                                },
                                new
                                {
                                    EventEntityId = 4,
                                    AdditionalInformation = "Streaming available",
                                    FloorNumber = 1,
                                    LocationType = 2,
                                    RoomNumber = 7
                                },
                                new
                                {
                                    EventEntityId = 5,
                                    AdditionalInformation = "Bring laptop",
                                    FloorNumber = 4,
                                    LocationType = 0,
                                    RoomNumber = 3
                                },
                                new
                                {
                                    EventEntityId = 6,
                                    AdditionalInformation = "Recording will be shared",
                                    FloorNumber = 0,
                                    LocationType = 1,
                                    RoomNumber = 0
                                },
                                new
                                {
                                    EventEntityId = 7,
                                    AdditionalInformation = "Open seating",
                                    FloorNumber = 6,
                                    LocationType = 0,
                                    RoomNumber = 21
                                },
                                new
                                {
                                    EventEntityId = 8,
                                    AdditionalInformation = "Workshop materials included",
                                    FloorNumber = 3,
                                    LocationType = 2,
                                    RoomNumber = 9
                                });
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("EventTypeEntity");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.Entities.EventTagEntity", b =>
                {
                    b.HasOne("Persistence.Entities.EventEntity", "EventEntity")
                        .WithMany("EventTags")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__EventTags__Event__571DF1D5");

                    b.HasOne("Persistence.Entities.TagEntity", "TagEntity")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK__EventTags__TagId__5812160E");

                    b.Navigation("EventEntity");

                    b.Navigation("TagEntity");
                });

            modelBuilder.Entity("Persistence.Entities.RegistrationEntity", b =>
                {
                    b.HasOne("Persistence.Entities.EventEntity", "EventEntity")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Event__5070F446");

                    b.HasOne("Persistence.Entities.RegistrationStatusEntity", "StatusEntity")
                        .WithMany("Registrations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Statu__52593CB8");

                    b.HasOne("Persistence.Entities.UserEntity", "UserEntity")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__UserI__5165187F");

                    b.Navigation("EventEntity");

                    b.Navigation("StatusEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("Persistence.IdentityModels.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("Persistence.Entities.UserEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Persistence.Entities.AgendaItemEntity", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Persistence.Entities.EventEntity", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("EventTags");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Persistence.Entities.EventTypeEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Persistence.Entities.RegistrationStatusEntity", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Persistence.Entities.TagEntity", b =>
                {
                    b.Navigation("EventTags");
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
